--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzli/UpdateNotifications
build-by-default: true
branches:
- stable
projects:
  UpdateNotifications:
    path: ""
    model: virion
    type: library
...
